// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEcv5apXCZNhNQjELjKvfg4pnBrWZIfvc',
    appId: '1:153757556487:android:4830a6072de47192d62fa2',
    messagingSenderId: '153757556487',
    projectId: 'test1-8850d',
    storageBucket: 'test1-8850d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpoZvB1Nf38N_ulG76kU6d6r5MJgTCYTY',
    appId: '1:153757556487:ios:699743163a3eb33fd62fa2',
    messagingSenderId: '153757556487',
    projectId: 'test1-8850d',
    storageBucket: 'test1-8850d.appspot.com',
    androidClientId: '153757556487-jrcmg7bg9p7s8ko1q1ts4jlfd47n0vmp.apps.googleusercontent.com',
    iosClientId: '153757556487-aif3dngg6c51cqnd8725l1luekjkln91.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
