// Mocks generated by Mockito 5.4.0 from annotations
// in tv/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:convert' as _i20;
import 'dart:typed_data' as _i21;

import 'package:core/tv/data/models/tv_model.dart' as _i18;
import 'package:core/tv/domain/entities/tv.dart' as _i13;
import 'package:core/utils/failure.dart' as _i12;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i9;
import 'package:tv/data/datasources/db/database_helper_tv.dart' as _i7;
import 'package:tv/data/datasources/tv_local_data_source.dart' as _i19;
import 'package:tv/data/datasources/tv_remote_data_source.dart' as _i17;
import 'package:tv/data/models/detail_season_model.dart' as _i4;
import 'package:tv/data/models/tv_detail_model.dart' as _i3;
import 'package:tv/data/models/tv_episode_model.dart' as _i5;
import 'package:tv/data/models/tv_table.dart' as _i10;
import 'package:tv/domain/entities/detail_season.dart' as _i15;
import 'package:tv/domain/entities/tv_detail.dart' as _i14;
import 'package:tv/domain/entities/tv_episode.dart' as _i16;
import 'package:tv/domain/repositories/tv_repository.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvDetailModel_1 extends _i1.SmartFake implements _i3.TvDetailModel {
  _FakeTvDetailModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDetailSeasonModel_2 extends _i1.SmartFake
    implements _i4.DetailSeasonModel {
  _FakeDetailSeasonModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvEpisodeModel_3 extends _i1.SmartFake
    implements _i5.TvEpisodeModel {
  _FakeTvEpisodeModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_4 extends _i1.SmartFake implements _i6.Response {
  _FakeResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_5 extends _i1.SmartFake
    implements _i6.StreamedResponse {
  _FakeStreamedResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseHelperTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelperTv extends _i1.Mock implements _i7.DatabaseHelperTv {
  MockDatabaseHelperTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i9.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i8.Future<_i9.Database?>.value(),
      ) as _i8.Future<_i9.Database?>);
  @override
  _i8.Future<int> insertWatchlist(_i10.TvTable? tv) => (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [tv],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);
  @override
  _i8.Future<int> removeWatchlist(_i10.TvTable? tv) => (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [tv],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);
  @override
  _i8.Future<Map<String, dynamic>?> getTvById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvById,
          [id],
        ),
        returnValue: _i8.Future<Map<String, dynamic>?>.value(),
      ) as _i8.Future<Map<String, dynamic>?>);
  @override
  _i8.Future<List<Map<String, dynamic>>> getWatchlistTvs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvs,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i11.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> getPopularTvs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvs,
          [],
        ),
        returnValue: _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #getPopularTvs,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);
  @override
  _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> getNowAiringTvs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowAiringTvs,
          [],
        ),
        returnValue: _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #getNowAiringTvs,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);
  @override
  _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> getTopRatedTvs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvs,
          [],
        ),
        returnValue: _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #getTopRatedTvs,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);
  @override
  _i8.Future<_i2.Either<_i12.Failure, _i14.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvDetail,
          [id],
        ),
        returnValue: _i8.Future<_i2.Either<_i12.Failure, _i14.TvDetail>>.value(
            _FakeEither_0<_i12.Failure, _i14.TvDetail>(
          this,
          Invocation.method(
            #getTvDetail,
            [id],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i12.Failure, _i14.TvDetail>>);
  @override
  _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> getTvsRecommendation(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvsRecommendation,
          [id],
        ),
        returnValue: _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #getTvsRecommendation,
            [id],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);
  @override
  _i8.Future<_i2.Either<_i12.Failure, _i15.DetailSeason>> getTvDetailSeason(
    int? tvId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvDetailSeason,
          [
            tvId,
            seasonNumber,
          ],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i12.Failure, _i15.DetailSeason>>.value(
                _FakeEither_0<_i12.Failure, _i15.DetailSeason>(
          this,
          Invocation.method(
            #getTvDetailSeason,
            [
              tvId,
              seasonNumber,
            ],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i12.Failure, _i15.DetailSeason>>);
  @override
  _i8.Future<_i2.Either<_i12.Failure, _i16.TvEpisode>> getTvDetailEpisode(
    int? tvId,
    int? seasonNumber,
    int? episodeNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvDetailEpisode,
          [
            tvId,
            seasonNumber,
            episodeNumber,
          ],
        ),
        returnValue: _i8.Future<_i2.Either<_i12.Failure, _i16.TvEpisode>>.value(
            _FakeEither_0<_i12.Failure, _i16.TvEpisode>(
          this,
          Invocation.method(
            #getTvDetailEpisode,
            [
              tvId,
              seasonNumber,
              episodeNumber,
            ],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i12.Failure, _i16.TvEpisode>>);
  @override
  _i8.Future<_i2.Either<_i12.Failure, String>> saveWatchlist(
          _i14.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [tv],
        ),
        returnValue: _i8.Future<_i2.Either<_i12.Failure, String>>.value(
            _FakeEither_0<_i12.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [tv],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i12.Failure, String>>);
  @override
  _i8.Future<_i2.Either<_i12.Failure, String>> removeWatchlist(
          _i14.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [tv],
        ),
        returnValue: _i8.Future<_i2.Either<_i12.Failure, String>>.value(
            _FakeEither_0<_i12.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [tv],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i12.Failure, String>>);
  @override
  _i8.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [id],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);
  @override
  _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> getTvsWatchlist() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvsWatchlist,
          [],
        ),
        returnValue: _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #getTvsWatchlist,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i17.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i18.TvModel>> getPopularTvs() => (super.noSuchMethod(
        Invocation.method(
          #getPopularTvs,
          [],
        ),
        returnValue: _i8.Future<List<_i18.TvModel>>.value(<_i18.TvModel>[]),
      ) as _i8.Future<List<_i18.TvModel>>);
  @override
  _i8.Future<List<_i18.TvModel>> getNowAiringTvs() => (super.noSuchMethod(
        Invocation.method(
          #getNowAiringTvs,
          [],
        ),
        returnValue: _i8.Future<List<_i18.TvModel>>.value(<_i18.TvModel>[]),
      ) as _i8.Future<List<_i18.TvModel>>);
  @override
  _i8.Future<List<_i18.TvModel>> getTopRatedTvs() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvs,
          [],
        ),
        returnValue: _i8.Future<List<_i18.TvModel>>.value(<_i18.TvModel>[]),
      ) as _i8.Future<List<_i18.TvModel>>);
  @override
  _i8.Future<_i3.TvDetailModel> getTvDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvDetail,
          [id],
        ),
        returnValue: _i8.Future<_i3.TvDetailModel>.value(_FakeTvDetailModel_1(
          this,
          Invocation.method(
            #getTvDetail,
            [id],
          ),
        )),
      ) as _i8.Future<_i3.TvDetailModel>);
  @override
  _i8.Future<List<_i18.TvModel>> getTvsRecommendation(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvsRecommendation,
          [id],
        ),
        returnValue: _i8.Future<List<_i18.TvModel>>.value(<_i18.TvModel>[]),
      ) as _i8.Future<List<_i18.TvModel>>);
  @override
  _i8.Future<_i4.DetailSeasonModel> getTvDetailSeason(
    int? tvId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvDetailSeason,
          [
            tvId,
            seasonNumber,
          ],
        ),
        returnValue:
            _i8.Future<_i4.DetailSeasonModel>.value(_FakeDetailSeasonModel_2(
          this,
          Invocation.method(
            #getTvDetailSeason,
            [
              tvId,
              seasonNumber,
            ],
          ),
        )),
      ) as _i8.Future<_i4.DetailSeasonModel>);
  @override
  _i8.Future<_i5.TvEpisodeModel> getTvDetailEpisode(
    int? tvId,
    int? seasonNumber,
    int? episodeNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvDetailEpisode,
          [
            tvId,
            seasonNumber,
            episodeNumber,
          ],
        ),
        returnValue: _i8.Future<_i5.TvEpisodeModel>.value(_FakeTvEpisodeModel_3(
          this,
          Invocation.method(
            #getTvDetailEpisode,
            [
              tvId,
              seasonNumber,
              episodeNumber,
            ],
          ),
        )),
      ) as _i8.Future<_i5.TvEpisodeModel>);
  @override
  _i8.Future<List<_i18.TvModel>> searchTvs(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvs,
          [query],
        ),
        returnValue: _i8.Future<List<_i18.TvModel>>.value(<_i18.TvModel>[]),
      ) as _i8.Future<List<_i18.TvModel>>);
}

/// A class which mocks [TvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvLocalDataSource extends _i1.Mock implements _i19.TvLocalDataSource {
  MockTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> insertWatchlist(_i10.TvTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [movie],
        ),
        returnValue: _i8.Future<String>.value(''),
      ) as _i8.Future<String>);
  @override
  _i8.Future<String> removeWatchlist(_i10.TvTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i8.Future<String>.value(''),
      ) as _i8.Future<String>);
  @override
  _i8.Future<_i10.TvTable?> getTvById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvById,
          [id],
        ),
        returnValue: _i8.Future<_i10.TvTable?>.value(),
      ) as _i8.Future<_i10.TvTable?>);
  @override
  _i8.Future<List<_i10.TvTable>> getWatchlistTvs() => (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvs,
          [],
        ),
        returnValue: _i8.Future<List<_i10.TvTable>>.value(<_i10.TvTable>[]),
      ) as _i8.Future<List<_i10.TvTable>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i6.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i20.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i20.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i20.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i20.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<String>.value(''),
      ) as _i8.Future<String>);
  @override
  _i8.Future<_i21.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i21.Uint8List>.value(_i21.Uint8List(0)),
      ) as _i8.Future<_i21.Uint8List>);
  @override
  _i8.Future<_i6.StreamedResponse> send(_i6.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i8.Future<_i6.StreamedResponse>.value(_FakeStreamedResponse_5(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i8.Future<_i6.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
